version: '3'

services:
  
  node-app: 
    build:
      context: node
    container_name: node_app
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s docker-entrypoint.sh node index.js
    restart: always
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - 3003:3003
    depends_on:
      - mysql-db

  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql_db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    
  nginx-proxy:
    build:
      context: ./nginx
    container_name: nginx_proxy
    ports:
      - 8080:80
    depends_on:
      - node-app
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge  