version: '3'

services:
  
  node: 
    restart: unless-stopped
    build:
      context: node
    container_name: node_app
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - desafio-nginx-node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports: 
      - 3003:3003
    depends_on:
      - mysql-db

  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql_db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - desafio-nginx-node-network
    
  nginx-proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks: 
      - desafio-nginx-node-network

networks: 
  desafio-nginx-node-network:
    driver: bridge  